name: CI

on: [push, pull_request]


jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      FC: gfortran

    steps:
    - name: Checkout code
      uses: actions/checkout@v1


    - name: Install gnuplot
      run: sudo apt install -y gnuplot

    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        format: 'YYYY-MM'

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest
